spring:
  # APPLICATION NAME
  application:
    name: auth-service
  # DB CONFIG
  datasource:
    url: jdbc:mysql://localhost:3306/auth_db
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    # HIBERNATE CONFIG
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

  main:
     allow-bean-definition-overriding: true

# SERVER CONFIG
server:
  port: 9001

