# SERVER PORT
server:
  port: 8070

spring:
  cloud:
    discovery:
      enabled: true
#    gateway:
#      routes:
#        - id: auth-service
#          uri: lb://auth-service
#          predicates:
#            - Path= /auth/**
#          filters:
#            - RewritePath=/auth/(?<path>.*), /$\{path} # redirecting /auth to auth-service
#        - id: blog-service
#          uri: lb://blog-service
#          predicates:
#            - Path= /blog/**
#          filters:
#            - RewritePath=/blog/(?<path>.*), /$\{path} # redirecting /blog to blog-service

  application:
    name: api-gateway # APPLICATION NAME
    gateway:
      discovery:
        locator:
          lowerCaseServiceId: true
          enabled: true


eureka:
  instance:
    hostname: localhost # EUREKA HOST
  client:
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka # EUREKA POINT